[package]
name = "exex-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.3" }
alloy-rpc-types-beacon = { git = "https://github.com/alloy-rs/alloy", tag = "v0.2.0", features = ["ssz"] }

eyre = "0.6.12"
futures = "0.3.30"
rand = "0.8.5"
tokio = "1.38.0"
reqwest = "0.12.5"
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }
tracing = "0.1.40"
thiserror = "1.0.63"
url = "2.5.2"
governor = "0.6.3"
flate2 = "1.0.30"
serde_with = "3.9.0"
alloy-primitives = "0.7.7"
primitive-types = "0.12.1"
chrono = "0.4.38"